baseURL = "https://reactos.org"
title = "ReactOS Website"
theme = "reactos"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
	name = "About"
	weight = 1
	[[menu.main]]
		parent = "About"
		name = "What is ReactOS?"
		url  = "/what-is-reactos"
		weight = 101
	[[menu.main]]
		parent = "About"
		name = "Gallery"
		url  = "/gallery"
		weight = 102
	[[menu.main]]
		parent = "About"
		name = "FAQ"
		url  = "/faq"
		weight = 103

[[menu.main]]
	name = "News"
	weight = 1
	[[menu.main]]
		parent = "News"
		name = "All News"
		url  = "/news/"
		weight = 101
	[[menu.main]]
		parent = "News"
		name = "Project News"
		url  = "/project-news/"
		weight = 102
	[[menu.main]]
		parent = "News"
		name = "Blog Posts"
		url  = "/blogs/"
		weight = 103

[[menu.main]]
	name = "Community"
	weight = 2
	[[menu.main]]
		parent = "Community"
		name = "Chat"
		url  = "https://chat.reactos.org"
		weight = 201
	[[menu.main]]
		parent = "Community"
		name = "Forum"
		url  = "/forum"
		weight = 202
	[[menu.main]]
		parent = "Community"
		name = "Shop"
		url  = "https://reactos.spreadshirt.net"
		weight = 203

[[menu.main]]
	name = "Development"
	weight = 3
	[[menu.main]]
		parent = "Development"
		name = "Architecture"
		url  = "/architecture"
		weight = 301
	[[menu.main]]
		parent = "Development"
		name = "Building ReactOS"
		url  = "https://reactos.org/wiki/Building_ReactOS"
		weight = 302
	[[menu.main]]
		parent = "Development"
		name = "Contributing"
		url  = "/contributing"
		weight = 303
	[[menu.main]]
		parent = "Development"
		name = "Download ReactOS Builds"
		url = "/getbuilds"
		weight = 304
	[[menu.main]]
		parent = "Development"
		name = "Jira"
		url  = "https://jira.reactos.org"
		weight = 310
	[[menu.main]]
		parent = "Development"
		name = "ReactOS on GitHub"
		url = "https://github.com/reactos"
		weight = 311
	[[menu.main]]
		parent = "Development"
		name = "Report a Bug"
		url  = "https://reactos.org/wiki/File_Bugs"
		weight = 312
	[[menu.main]]
		parent = "Development"
		name = "Testman"
		url  = "/testman"
		weight = 313
	[[menu.main]]
		parent = "Development"
		name = "Wiki"
		url  = "/wiki"
		weight = 314
	[[menu.main]]
		parent = "Development"
		name = "Work for ReactOS"
		url  = "/contributing#paid-jobs"
		weight = 315

[[menu.main]]
	name = "Donate"
	url  = "/donate"
	weight = 5

[[menu.main]]
	name = "Download"
	url  = "/download"
	weight = 6

[params]
	viewMorePostLink = "/news/"
	author = "DevCows"
	defaultKeywords = ["ReactOS", "react", "os", "open source", "free", "win32", "winapi"]
	defaultDescription = "ReactOS is a free, opensource reimplementation of windows"

	# Format dates with Go's time formatting
	date_format = "January 2, 2006"

	logo = "/sites/default/files/ReactOS_0.png"
	logo_small = "/sites/default/files/ReactOS_0.png"

	development_banner_text = "DEVELOPMENT COPY!"

[Permalinks]
	blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
	categories = true
	tags = true
	search = true

[taxonomies]
	author = "author"
	tag = "tags"
